# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: direction.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "DirectionPb.Calculate" do
  end
  add_message "DirectionPb.Calculate.Request" do
    optional :startPoint, :message, 1, "DirectionPb.Calculate.Point"
    optional :endPoint, :message, 2, "DirectionPb.Calculate.Point"
  end
  add_message "DirectionPb.Calculate.Response" do
    optional :distance, :double, 1
    optional :time, :int64, 2
  end
  add_message "DirectionPb.Calculate.Point" do
    optional :lat, :double, 1
    optional :lng, :double, 2
  end
end

module DirectionPb
  Calculate = Google::Protobuf::DescriptorPool.generated_pool.lookup("DirectionPb.Calculate").msgclass
  Calculate::Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("DirectionPb.Calculate.Request").msgclass
  Calculate::Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("DirectionPb.Calculate.Response").msgclass
  Calculate::Point = Google::Protobuf::DescriptorPool.generated_pool.lookup("DirectionPb.Calculate.Point").msgclass
end
