// Code generated by protoc-gen-go. DO NOT EDIT.
// source: direction.proto

package DirectionPb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Calculate struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculate) Reset()         { *m = Calculate{} }
func (m *Calculate) String() string { return proto.CompactTextString(m) }
func (*Calculate) ProtoMessage()    {}
func (*Calculate) Descriptor() ([]byte, []int) {
	return fileDescriptor_direction_b7c5e22a0da22bb9, []int{0}
}
func (m *Calculate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculate.Unmarshal(m, b)
}
func (m *Calculate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculate.Marshal(b, m, deterministic)
}
func (dst *Calculate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculate.Merge(dst, src)
}
func (m *Calculate) XXX_Size() int {
	return xxx_messageInfo_Calculate.Size(m)
}
func (m *Calculate) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculate.DiscardUnknown(m)
}

var xxx_messageInfo_Calculate proto.InternalMessageInfo

type Calculate_Request struct {
	StartPoint           *Calculate_Point `protobuf:"bytes,1,opt,name=startPoint,proto3" json:"startPoint,omitempty"`
	EndPoint             *Calculate_Point `protobuf:"bytes,2,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Calculate_Request) Reset()         { *m = Calculate_Request{} }
func (m *Calculate_Request) String() string { return proto.CompactTextString(m) }
func (*Calculate_Request) ProtoMessage()    {}
func (*Calculate_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_direction_b7c5e22a0da22bb9, []int{0, 0}
}
func (m *Calculate_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculate_Request.Unmarshal(m, b)
}
func (m *Calculate_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculate_Request.Marshal(b, m, deterministic)
}
func (dst *Calculate_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculate_Request.Merge(dst, src)
}
func (m *Calculate_Request) XXX_Size() int {
	return xxx_messageInfo_Calculate_Request.Size(m)
}
func (m *Calculate_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculate_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Calculate_Request proto.InternalMessageInfo

func (m *Calculate_Request) GetStartPoint() *Calculate_Point {
	if m != nil {
		return m.StartPoint
	}
	return nil
}

func (m *Calculate_Request) GetEndPoint() *Calculate_Point {
	if m != nil {
		return m.EndPoint
	}
	return nil
}

type Calculate_Response struct {
	Distance             float64  `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculate_Response) Reset()         { *m = Calculate_Response{} }
func (m *Calculate_Response) String() string { return proto.CompactTextString(m) }
func (*Calculate_Response) ProtoMessage()    {}
func (*Calculate_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_direction_b7c5e22a0da22bb9, []int{0, 1}
}
func (m *Calculate_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculate_Response.Unmarshal(m, b)
}
func (m *Calculate_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculate_Response.Marshal(b, m, deterministic)
}
func (dst *Calculate_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculate_Response.Merge(dst, src)
}
func (m *Calculate_Response) XXX_Size() int {
	return xxx_messageInfo_Calculate_Response.Size(m)
}
func (m *Calculate_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculate_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Calculate_Response proto.InternalMessageInfo

func (m *Calculate_Response) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Calculate_Response) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Calculate_Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculate_Point) Reset()         { *m = Calculate_Point{} }
func (m *Calculate_Point) String() string { return proto.CompactTextString(m) }
func (*Calculate_Point) ProtoMessage()    {}
func (*Calculate_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_direction_b7c5e22a0da22bb9, []int{0, 2}
}
func (m *Calculate_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculate_Point.Unmarshal(m, b)
}
func (m *Calculate_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculate_Point.Marshal(b, m, deterministic)
}
func (dst *Calculate_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculate_Point.Merge(dst, src)
}
func (m *Calculate_Point) XXX_Size() int {
	return xxx_messageInfo_Calculate_Point.Size(m)
}
func (m *Calculate_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculate_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Calculate_Point proto.InternalMessageInfo

func (m *Calculate_Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Calculate_Point) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func init() {
	proto.RegisterType((*Calculate)(nil), "DirectionPb.Calculate")
	proto.RegisterType((*Calculate_Request)(nil), "DirectionPb.Calculate.Request")
	proto.RegisterType((*Calculate_Response)(nil), "DirectionPb.Calculate.Response")
	proto.RegisterType((*Calculate_Point)(nil), "DirectionPb.Calculate.Point")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirectionClient is the client API for Direction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirectionClient interface {
	Calculate(ctx context.Context, in *Calculate_Request, opts ...grpc.CallOption) (*Calculate_Response, error)
}

type directionClient struct {
	cc *grpc.ClientConn
}

func NewDirectionClient(cc *grpc.ClientConn) DirectionClient {
	return &directionClient{cc}
}

func (c *directionClient) Calculate(ctx context.Context, in *Calculate_Request, opts ...grpc.CallOption) (*Calculate_Response, error) {
	out := new(Calculate_Response)
	err := c.cc.Invoke(ctx, "/DirectionPb.Direction/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectionServer is the server API for Direction service.
type DirectionServer interface {
	Calculate(context.Context, *Calculate_Request) (*Calculate_Response, error)
}

func RegisterDirectionServer(s *grpc.Server, srv DirectionServer) {
	s.RegisterService(&_Direction_serviceDesc, srv)
}

func _Direction_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Calculate_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectionServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DirectionPb.Direction/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectionServer).Calculate(ctx, req.(*Calculate_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Direction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DirectionPb.Direction",
	HandlerType: (*DirectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _Direction_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "direction.proto",
}

func init() { proto.RegisterFile("direction.proto", fileDescriptor_direction_b7c5e22a0da22bb9) }

var fileDescriptor_direction_b7c5e22a0da22bb9 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbf, 0x4b, 0xc7, 0x30,
	0x14, 0xc4, 0x89, 0x5f, 0x7f, 0xb4, 0xaf, 0x83, 0xf2, 0x26, 0x09, 0xa2, 0xe2, 0x24, 0x08, 0x19,
	0xea, 0x22, 0xe2, 0xa6, 0xa3, 0x43, 0xc9, 0xe6, 0x98, 0xb6, 0x8f, 0x12, 0xa8, 0x49, 0x6d, 0x5e,
	0xff, 0x00, 0xff, 0x6b, 0x47, 0x69, 0x5a, 0x43, 0x97, 0x82, 0xdb, 0xe5, 0x72, 0x9f, 0xe4, 0x38,
	0x38, 0x6f, 0xed, 0x48, 0x0d, 0x5b, 0xef, 0xd4, 0x30, 0x7a, 0xf6, 0x58, 0xbc, 0xfd, 0x19, 0x55,
	0x7d, 0xf7, 0x23, 0x20, 0x7f, 0x35, 0x7d, 0x33, 0xf5, 0x86, 0x49, 0x7e, 0x0b, 0x38, 0xd3, 0xf4,
	0x35, 0x51, 0x60, 0x7c, 0x01, 0x08, 0x6c, 0x46, 0xae, 0xbc, 0x75, 0x7c, 0x29, 0x6e, 0xc5, 0x7d,
	0x51, 0x5e, 0xa9, 0x0d, 0xab, 0x12, 0xa7, 0x62, 0x46, 0x6f, 0xf2, 0xf8, 0x04, 0x19, 0xb9, 0x76,
	0x61, 0x8f, 0xfe, 0xc1, 0xa6, 0xb4, 0x7c, 0x86, 0x4c, 0x53, 0x18, 0xbc, 0x0b, 0x84, 0x12, 0xb2,
	0xd6, 0x06, 0x36, 0xae, 0xa1, 0xd8, 0x40, 0xe8, 0x74, 0x46, 0x84, 0x63, 0xb6, 0x9f, 0x14, 0x5f,
	0x3f, 0xe8, 0xa8, 0xe5, 0x03, 0x9c, 0x2c, 0xdf, 0x5f, 0xc0, 0xa1, 0x37, 0xbc, 0x32, 0xb3, 0x8c,
	0x8e, 0xeb, 0x62, 0x7a, 0x76, 0x5c, 0x57, 0x7e, 0x40, 0x9e, 0x1a, 0xe1, 0xfb, 0x66, 0x06, 0xbc,
	0xde, 0xa9, 0xba, 0x4e, 0x23, 0x6f, 0x76, 0xef, 0x97, 0xde, 0xf5, 0x69, 0x5c, 0xfa, 0xf1, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x09, 0x3f, 0xb6, 0x34, 0x7c, 0x01, 0x00, 0x00,
}
